const perguntasIngles = {
  "7ano": [
    { texto: "Read the sentence: 'I usually wake up at 6:30 a.m. and go to school by bus.' What is the main idea of the sentence?", alternativas: ["The student likes going to the beach.", "The student describes his daily routine.", "The student is studying at night.", "The student is traveling to another country."], respostaCorreta: 1, explicacao: "The sentence presents a routine, with time and daily action.", dificuldade: "facil", tipo: "interpretacao" },
    { texto: "Choose the sentence that is correct:", alternativas: ["She don't like coffee.", "She doesn't likes coffee.", "She doesn't like coffee.", "She not like coffee."], respostaCorreta: 2, explicacao: "'Doesn't' requires the base form of the verb: 'like'.", dificuldade: "facil", tipo: "gramatica" },
    { texto: "In the sentence 'The book is under the table', the word 'under' indicates:", alternativas: ["time", "place", "reason", "manner"], respostaCorreta: 1, explicacao: "'Under' shows position, so it indicates place.", dificuldade: "media", tipo: "preposicao" },
    { texto: "Which sentence is in the simple present?", alternativas: ["I was reading a book.", "I read books every day.", "I will read a book tomorrow.", "I have read the book."], respostaCorreta: 1, explicacao: "'I read books every day' expresses a habit in the present.", dificuldade: "media", tipo: "tempo_verbal" },
    { texto: "A student says: 'I am tired because I studied all night.' The reason is:", alternativas: ["Because he slept well.", "Because he studied all night.", "Because he went to the park.", "Because he woke up early."], respostaCorreta: 1, explicacao: "The sentence gives a clear reason: studying all night made him tired.", dificuldade: "media", tipo: "interpretacao" },
    { texto: "Which is the correct plural of 'child'?", alternativas: ["childs", "children", "childes", "childer"], respostaCorreta: 1, explicacao: "'Child' is irregular; its plural is 'children'.", dificuldade: "media", tipo: "vocabulario" }
  ],
  "8ano": [
    { texto: "Read: 'If it rains tomorrow, we will stay home.' This sentence expresses:", alternativas: ["a past action", "a future possibility", "a habit", "an order"], respostaCorreta: 1, explicacao: "The sentence uses the first conditional, which describes a real future possibility.", dificuldade: "media", tipo: "condicional" },
    { texto: "Choose the most appropriate answer: 'Can you help me with this exercise?' '_____, of course.'", alternativas: ["No way", "Sure", "Perhaps", "Later"], respostaCorreta: 1, explicacao: "'Sure' is the natural response to accepting help.", dificuldade: "facil", tipo: "dialogo" },
    { texto: "In the sentence 'The teacher explained the lesson clearly', the adverb is:", alternativas: ["teacher", "lesson", "clearly", "explained"], respostaCorreta: 2, explicacao: "'Clearly' modifies the verb 'explained'.", dificuldade: "facil", tipo: "gramatica" },
    { texto: "A notice says: 'No smoking inside the building.' The warning means:", alternativas: ["Smoking is allowed in the building.", "Smoking is forbidden inside the building.", "The building is closed today.", "People must smoke outside only."], respostaCorreta: 1, explicacao: "'No smoking' is a prohibition, so smoking is not allowed inside.", dificuldade: "media", tipo: "interpretacao" },
    { texto: "Choose the sentence with the correct comparative form:", alternativas: ["This test is more difficult than the last one.", "This test is difficulter than the last one.", "This test is most difficult than the last one.", "This test is difficulter than the last one."], respostaCorreta: 0, explicacao: "Comparatives with long adjectives use 'more + adjective'.", dificuldade: "media", tipo: "comparacao" },
    { texto: "The phrase 'at the same time' is used to express:", alternativas: ["cause", "contrast", "simultaneity", "condition"], respostaCorreta: 2, explicacao: "The expression refers to two actions happening at the same moment.", dificuldade: "dificil", tipo: "contextualizacao" }
  ],
  "9ano": [
    { texto: "Read: 'Although the train was delayed, Maria arrived on time for the interview.' What does 'Although' show?", alternativas: ["Cause", "Purpose", "Contrast", "Result"], respostaCorreta: 2, explicacao: "'Although' introduces a contrast between delay and arrival on time.", dificuldade: "media", tipo: "conectores" },
    { texto: "Which sentence is in the passive voice?", alternativas: ["The teacher explained the topic.", "The topic was explained by the teacher.", "The teacher explains the topic.", "The students discuss the topic."], respostaCorreta: 1, explicacao: "The passive voice focuses on the action received by the subject: 'The topic was explained'.", dificuldade: "media", tipo: "voz_passiva" },
    { texto: "What is the meaning of the phrasal verb 'give up'?", alternativas: ["continue", "abandon", "repair", "enter"], respostaCorreta: 1, explicacao: "'Give up' means to stop trying or abandon an effort.", dificuldade: "media", tipo: "vocabulario" },
    { texto: "You receive an email that says: 'We would appreciate your prompt response.' This request is:", alternativas: ["very informal", "polite and urgent", "a joke", "a command without reason"], respostaCorreta: 1, explicacao: "The expression is formal and polite, while also indicating urgency.", dificuldade: "media", tipo: "interpretacao" },
    { texto: "Choose the correct sentence:", alternativas: ["If I was you, I would apologize.", "If I were you, I would apologize.", "If I am you, I would apologize.", "If I was been you, I would apologize."], respostaCorreta: 1, explicacao: "After 'if' in hypothetical situations, the correct form is 'were'.", dificuldade: "dificil", tipo: "condicional" },
    { texto: "The sentence 'The company has reduced its emissions' suggests that:", alternativas: ["emissions increased", "emissions were lowered", "the company closed", "the company started using more plastic"], respostaCorreta: 1, explicacao: "'Reduced' means that emissions were decreased.", dificuldade: "media", tipo: "vocabulario" }
  ],
  "1medio": [
    { texto: "Read the following notice: 'Please keep your seatbelt fastened during the flight.' The main purpose is to:", alternativas: ["entertain passengers", "warn about safety rules", "describe the plane's speed", "ask passengers to leave the plane"], respostaCorreta: 1, explicacao: "The notice gives a safety instruction to passengers.", dificuldade: "media", tipo: "interpretacao" },
    { texto: "Which sentence is correct?", alternativas: ["By the time I arrived, they had left.", "By the time I arrived, they leave.", "By the time I arrived, they were leave.", "By the time I arrived, they have left."], respostaCorreta: 0, explicacao: "The past perfect is used to show an action completed before another past action.", dificuldade: "dificil", tipo: "tempo_verbal" },
    { texto: "The expression 'make an effort' means:", alternativas: ["do nothing", "try hard", "forget the task", "start a fire"], respostaCorreta: 1, explicacao: "'Make an effort' means to try seriously and with intention.", dificuldade: "media", tipo: "vocabulario" },
    { texto: "A school announcement says: 'The meeting will begin promptly at 8:00 p.m.' This means:", alternativas: ["the meeting will begin late", "the meeting will begin on time", "the meeting is canceled", "students may come at any time"], respostaCorreta: 1, explicacao: "'Promptly' indicates that the meeting begins exactly at the scheduled time.", dificuldade: "media", tipo: "contextualizacao" },
    { texto: "Choose the option that completes the sentence: 'If we ___ more time, we would finish the project.'", alternativas: ["have", "had", "will have", "are having"], respostaCorreta: 1, explicacao: "This is a second conditional sentence, which uses 'had'.", dificuldade: "dificil", tipo: "condicional" },
    { texto: "In formal writing, a sentence like 'We appreciate your cooperation' is best described as:", alternativas: ["very informal", "formal and respectful", "a joke", "a command without explanation"], respostaCorreta: 1, explicacao: "The phrase is polite, professional and appropriate for formal communication.", dificuldade: "media", tipo: "contextualizacao" }
  ],
  "2medio": [
    { texto: "Read the statement: 'The rise in online learning has changed how students study.' The best inference is that:", alternativas: ["students no longer need teachers", "education is now more flexible and digital", "online learning is the only option", "students never study at home"], respostaCorreta: 1, explicacao: "The statement suggests that online learning modified the way students learn, making it more digital and flexible.", dificuldade: "media", tipo: "inferencia" },
    { texto: "Which sentence demonstrates a formal tone?", alternativas: ["Hey, can you send the file?", "Please send the file as soon as possible.", "Send it now!", "Yo, file me!"], respostaCorreta: 1, explicacao: "The second sentence uses a formal and polite tone appropriate for institutional communication.", dificuldade: "media", tipo: "registro" },
    { texto: "The phrase 'carry out research' means:", alternativas: ["stop studying", "conduct a study", "write a poem", "ignore the results"], respostaCorreta: 1, explicacao: "'Carry out research' means to perform a research activity or investigation.", dificuldade: "media", tipo: "vocabulario" },
    { texto: "In a report, the sentence 'This issue has become increasingly relevant in recent years' expresses:", alternativas: ["a personal opinion without evidence", "an evaluation of growing importance", "a command", "a simple fact without relevance"], respostaCorreta: 1, explicacao: "The sentence presents a trend and indicates growing importance over time.", dificuldade: "dificil", tipo: "interpretacao" },
    { texto: "Choose the correct reported speech: 'He said, “I am tired.”'", alternativas: ["He said that he is tired.", "He said that he was tired.", "He said that I was tired.", "He said that I am tired."], respostaCorreta: 1, explicacao: "In reported speech, the verb usually shifts back one tense: 'am' becomes 'was'.", dificuldade: "dificil", tipo: "reported_speech" },
    { texto: "Which statement best reflects a persuasive text?", alternativas: ["It describes only facts without trying to influence.", "It presents a point of view and tries to convince the reader.", "It is only a list of events.", "It is written only in fragments and without structure."], respostaCorreta: 1, explicacao: "Persuasive texts aim to convince the audience by presenting arguments and opinions.", dificuldade: "media", tipo: "argumentacao" }
  ],
  "3medio": [
    { texto: "Read the excerpt: 'The survey revealed that students who use digital tools regularly tend to organize their work better.' The statement suggests that:", alternativas: ["technology has no impact on study habits", "digital tools can influence organization and planning", "students should never use technology", "digital tools are always distracting"], respostaCorreta: 1, explicacao: "The sentence presents a likely positive relationship between technology use and organization.", dificuldade: "media", tipo: "inferencia" },
    { texto: "Which phrase is most appropriate in an academic presentation?", alternativas: ["This is super important, guys.", "This issue is highly relevant to the discussion.", "This topic is totally cool.", "It is kind of a big deal."], respostaCorreta: 1, explicacao: "Academic language should be precise, formal and objective.", dificuldade: "media", tipo: "registro" },
    { texto: "Complete: 'By the time the professor arrived, the students ____ the discussion.'", alternativas: ["have finished", "had finished", "finish", "were finishing"], respostaCorreta: 1, explicacao: "The past perfect 'had finished' shows an action completed before another past action.", dificuldade: "dificil", tipo: "tempo_verbal" },
    { texto: "Choose the sentence that is most cohesive in an argumentative paragraph:", alternativas: ["The topic is important. The school is big. The teacher is kind.", "The topic is important because it affects students directly and requires practical solutions.", "The students are in class. It is morning.", "The school has many chairs. Chairs are comfortable."], respostaCorreta: 1, explicacao: "The second sentence develops the central idea with relevance and logical connection.", dificuldade: "media", tipo: "coesao" },
    { texto: "The phrase 'in light of' is closest in meaning to:", alternativas: ["because of", "in spite of", "during", "without"], respostaCorreta: 0, explicacao: "'In light of' means 'considering' or 'because of'.", dificuldade: "dificil", tipo: "vocabulario" },
    { texto: "A good argumentative text should:", alternativas: ["ignore evidence and rely only on emotion", "present a clear position supported by reasons and examples", "repeat the same idea without development", "avoid any connection to real-life situations"], respostaCorreta: 1, explicacao: "A solid argument uses reasons, examples and clear organization to support a point of view.", dificuldade: "media", tipo: "argumentacao" }
  ]
};

// A revisão das perguntas prioriza interpretação de contexto, uso real da língua e raciocínio,
// mantendo a arquitetura atual do quiz e deixando cada item mais plausível e pedagógico.
if (typeof window !== 'undefined') {
  Object.values(perguntasIngles).flat().forEach((questao) => {
    questao.fonte = questao.fonte || 'https://basenacionalcomum.mec.gov.br/';
  });
  window.perguntasIngles = perguntasIngles;
}
